name: C/C++ CI

on:
  workflow_call:          # Makes this workflow callable from other workflows
    inputs:
      build_type:         # Optional input example
        required: false
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - uses: actions/checkout@v4

      - name: make
        run: |
          echo "Build type: ${{ inputs.build_type }}"
          make
